# Generated by Django 4.1 on 2022-09-03 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('balanace', models.FloatField()),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipments',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('langitude', models.FloatField()),
                ('lotitude', models.FloatField()),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ReportOfWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_work', models.CharField(max_length=100, verbose_name='Title of work')),
                ('comment', models.TextField(blank=True, null=True)),
                ('measure', models.CharField(max_length=64, null=True)),
                ('count_of_work', models.IntegerField(null=True, verbose_name='Count of work')),
                ('price', models.FloatField()),
                ('summa', models.BigIntegerField(blank=True, null=True)),
                ('comment_of_admin', models.TextField(blank=True, null=True, verbose_name='Comment of admin')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportofworks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportofworks', to='reports.project')),
            ],
            options={
                'verbose_name': 'Report of Works',
                'verbose_name_plural': 'Reports of Works',
            },
        ),
        migrations.CreateModel(
            name='ReportOfMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_report', models.CharField(max_length=100, verbose_name='Name of Report')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportofmonths', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report of Month',
                'verbose_name_plural': 'Reports of Month',
            },
        ),
        migrations.CreateModel(
            name='ReportOfInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(max_length=100)),
                ('what_work', models.CharField(max_length=200, verbose_name='What Work')),
                ('who_fuel_taken_from', models.CharField(max_length=200, verbose_name='Who Fuel Taken From')),
                ('taken_amount_of_fuel', models.FloatField(verbose_name='Taken Amount of Fuel')),
                ('spending_fuel', models.FloatField(verbose_name='Spending Fuel')),
                ('price_of_fuel', models.IntegerField(verbose_name='Price of Fuel')),
                ('measure_of_work', models.CharField(max_length=64, null=True, verbose_name='Measure of Work')),
                ('work_time', models.IntegerField(verbose_name='Work Time')),
                ('work_price', models.FloatField(verbose_name='Price of Work')),
                ('money_worked', models.BigIntegerField(verbose_name='Money Worked')),
                ('exponse', models.IntegerField(blank=True, null=True)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportofinstruments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportofinstruments', to='reports.project')),
            ],
        ),
        migrations.CreateModel(
            name='ReportOfDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_of_reports', models.IntegerField(verbose_name='Count of Reports')),
                ('status_of_report', models.CharField(max_length=100, verbose_name='Status of Report')),
                ('report_of_inout', models.BooleanField(verbose_name='InOut')),
                ('report_of_works', models.BooleanField(verbose_name='Works')),
                ('report_of_expenses', models.BooleanField(verbose_name='Expenses')),
                ('report_of_instruments', models.BooleanField(verbose_name='Instruments')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportofdays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report of Day',
                'verbose_name_plural': 'Reports of Day',
            },
        ),
        migrations.CreateModel(
            name='ExpensesOfMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=200, null=True)),
                ('income', models.BigIntegerField(blank=True, null=True)),
                ('outlay', models.BigIntegerField(blank=True, null=True)),
                ('remaining_summ', models.BigIntegerField(blank=True, null=True, verbose_name='Remaining Summ')),
                ('all_income', models.BigIntegerField(blank=True, null=True, verbose_name='All Income')),
                ('all_outlay', models.BigIntegerField(blank=True, null=True, verbose_name='All Outlay')),
                ('all_remining_summ', models.BigIntegerField(blank=True, null=True, verbose_name='All Remaining Summ')),
                ('comment_of_admin', models.TextField(blank=True, null=True, verbose_name='Comment of Admin')),
                ('given_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expensesofmoney_given', to=settings.AUTH_USER_MODEL, verbose_name='Manager Taken')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expensesofmoney', to='reports.project')),
                ('taken_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expensesofmoney', to=settings.AUTH_USER_MODEL, verbose_name='Manager Given')),
            ],
            options={
                'verbose_name': 'Expenses of Money',
                'verbose_name_plural': 'Expenses of Money',
            },
        ),
    ]
