# Generated by Django 4.1 on 2022-09-03 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportOfInOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker', models.CharField(max_length=100)),
                ('work_time', models.IntegerField(verbose_name='Work time')),
                ('all_work_time', models.IntegerField(verbose_name='All work time')),
                ('day_wage', models.FloatField(verbose_name='Day wage')),
                ('salary', models.FloatField()),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportofinouts', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportofinouts', to='reports.project')),
            ],
            options={
                'verbose_name': 'Report of InOut',
                'verbose_name_plural': 'Reports of InOut',
            },
        ),
        migrations.CreateModel(
            name='ReportOfEquipmentInOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('which_project_to', models.CharField(max_length=100, verbose_name='Which Project To')),
                ('which_manager_to', models.CharField(max_length=100, verbose_name='Which Manager To')),
                ('status', models.CharField(choices=[('New', 'New'), ('Used', 'Used')], default='New', max_length=64)),
                ('count', models.IntegerField()),
                ('income_count', models.IntegerField(blank=True, null=True, verbose_name='Income Count')),
                ('outlay_count', models.IntegerField(blank=True, null=True, verbose_name='Outlay Count')),
                ('comment', models.TextField(blank=True, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportofequipmentinouts', to='reports.equipment')),
                ('which_manager_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportofequipmentinouts', to=settings.AUTH_USER_MODEL, verbose_name='Which Manager From')),
                ('which_project_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportofequipmentinouts', to='reports.project', verbose_name='Which Project From')),
            ],
            options={
                'verbose_name': 'Report of Equipment InOut',
                'verbose_name_plural': 'Reports of Equipment InOut',
            },
        ),
    ]
